### ISSUE TITLE
Improve Dot Visualization for the Visualization Page

### ISSUE THREAD

**Issue by TebogoYungMercykay** [COS301-SE-2024/The-Republic#133]
This will provide users with an interactive and intuitive way to explore the data.

### Tasks
- [ ] Connect the visualization to the backend to fetch relevant data
- [ ] Write unit tests for the visualization component
- [ ] Have a legend and color for the different categories. So for example the color blue can be shown as for water and sanitation.
- [ ] Work on saturation with a darker color meaning intense and a lighter color meaning not that intense. This relates to the number of issues pertaining to the specific category.

### Documentation
https://observablehq.com/@d3/zoomable-circle-packing
