### ISSUE TITLE
Report page graph improvements

### ISSUE THREAD

**Issue by hlokomani** [COS301-SE-2024/The-Republic#150]
Our client has highlighted some improvements that must be made to the reports page. This issue seeks to address those concerns. 

### To-do:
- [x] Carefully consider which graphs are not useful and remove them.
- [x] Create a feature that allows users to pick which graphs they would like to see. 
For example: If a user just want's to see a bar graph, then they should be able to do that.
- [ ] Create a component that allows users to pick certain locations that their data must be filtered against
NB: This is *not* like the Google Autocomplete feature on the IssueInputBox component. This instead must fetch existing location that are stored in the database.

### Example/References:
https://ui.shadcn.com/docs/components/combobox
