### ISSUE TITLE
Implement access requests form

### ISSUE THREAD

**Issue by hlokomani** [COS301-SE-2024/The-Republic#154]
This is the feature that will unlock the external resolution feature. Lots of interesting data can be extracted here so it is important that we ask the right questions that can be used for our data visualization and reporting.

### To-do:
The form should ask at minimum the following:
- [ ] Full name
- [ ] ID Number (to safeguard us against those officials that abuse the application)
- [ ] Political affiliation (should not be compulsory, but if they pick one they must be a registered member of said organization)
- [ ] What part of the state they work for (tricky)
This is not just departments. This will also be people like councilors, Eskom technicians, water entity worker etc.
- [ ] Upload any form of proof as pdf
