### ISSUE TITLE
Add moderation for images

### ISSUE THREAD

**Issue by IRIA7** [COS301-SE-2024/The-Republic#166]
Images need to be moderated to prevent harmful content in the app

### Todo
- [x] Create an Azure account
- [x] Add image moderation when creating issues 
- [x] Add image moderation when uploading profile pictures

### References
- https://learn.microsoft.com/en-us/azure/ai-services/content-safety/overview
