### ISSUE TITLE
Revise and enhance user manual

### ISSUE THREAD

**Issue by MulisaMusehane** [COS301-SE-2024/The-Republic#197]
**Description**
Update the user manual to reflect the current system and implemented use cases.
Use layperson's terms and include graphical models and non-technical descriptions.

**Tasks**
- [ ] Describe the project in simple terms.
- [ ] Include graphical models and pictures.
- [ ] Detail the implemented use cases for this demo that we added.
