### ISSUE TITLE
Update and create technical installation manual

### ISSUE THREAD

**Issue by MulisaMusehane** [COS301-SE-2024/The-Republic#198]
**Description**
Detail all necessary information to clone the main branch and configure the system to run and install.
Include installation of additional software needed by the system.
Cater for multiple operating systems if necessary.

**Tasks**
- [ ] Write an introduction explaining the system and its components.
- [ ] List prerequisites and provide installation resources.
- [ ] Describe the installation process step-by-step.
- [ ] Detail the deployment/running instructions.
- [ ] Include version numbers for packages and dependencies.
- [ ] Add detailed instructions with screenshots.
