### ISSUE TITLE
Update definitions and quantify quality requirements

### ISSUE THREAD

**Issue by MulisaMusehane** [COS301-SE-2024/The-Republic#199]
**Description**
Specify and quantify quality requirements relevant to the system.
Include performance, reliability, scalability, security, maintainability, and usability.
Ensure requirements are quantifiable or specified in a testable way.

**Tasks**
- [ ] Update list of all relevant quality requirements if necessary.
- [ ] Provide quantifiable metrics or testable specifications for each requirement - strictly according to our system and in detail.
- [ ] Explain how the architectural patterns address these quality requirements  - refer to the diagram as well.
