### ISSUE TITLE
Implement Subscription Management in Backend

### ISSUE THREAD

**Issue by TebogoYungMercykay** [COS301-SE-2024/The-Republic#207]
This is a hefty ticket. The goal is to implement backend support for subscription management. Users should be able to subscribe to issues, categories, or locations and manage their subscriptions (ie delete them if they would like). Integrate Supabase Realtime for real-time notifications.

The prerequisite to this ticket being completed successfully is the Location ticket being completed. So first check if that has been completed before starting this.

**Subtasks:**

- [x] Create `subscriptions` table in the database.
- [x] Create `notifications` table in the database.
- [x] Index the user_id, created_at fields for quicker query time
- [x] Implement `SubscriptionRepository`.
- [x] Implement `SubscriptionService`.
- [x] Implement `SubscriptionController`.
- [x] Create routes for `SubscriptionController`
- [x] Write unit tests for service layer methods

For help:
- https://supabase.com/docs/guides/realtime?queryGroups=language&language=js
- Look into triggers and functions on Supabase.
