### ISSUE TITLE
Organization Membership Management

### ISSUE THREAD

**Issue by hlokomani** [COS301-SE-2024/The-Republic#282]
## Objective
Implement frontend features for users to join organizations and for admins to manage membership.

## Tasks
- [x] Design and implement UI for users to join or request to join organizations
- [x] Create an interface for admins to set and change join policy
- [x] Implement admin interface to approve/reject join requests
- [x] Design UI for admins to manage members (view, remove)
- [ ] Create notifications UI for membership status changes

## Acceptance Criteria
- Users see appropriate join options based on organization's join policy
- Admins can easily change join policy from the organization settings
- For 'request_to_join' policy, admins have a clear interface to manage requests
- Admins can view all members and remove them if necessary
