### ISSUE TITLE
Issue component optimization

### ISSUE THREAD

**Issue by hlokomani** [COS301-SE-2024/The-Republic#306]
## Objective
Enhance performance of frontend by moving a lot of the calls made on the Issue component to the backend. Right now, there are about 5 calls being made for one component. That being
- Fetching of the issues
- Fetching related issues for each issue
- Fetching whether the logged in user has issues in the cluster of each issue
- Fetching the resolutions
- Fetching whether the user can respond to that resolution

## Tasks
- [ ] Remove all the above API calls from the frontend
- [ ] Make the getIssues endpoint return all necessary fields instead
- [ ] Limit the number of related issues to be fetched to 3
- [ ] Integrate this new return structure to the component and related modals
