### ISSUE TITLE
Removal of mood throughout the system

### ISSUE THREAD

**Issue by hlokomani** [COS301-SE-2024/The-Republic#308]
## Objective
Following our meeting with the client, we have agreed to remove the mood of each post as this is not necessary anymore. The platform exists for users to voice their concerns and issues, excuse the pun, that they face. So sentiment data is not really relevant as the use case of a user coming on the platform to log a compliment to a certain organization is negligible. 

## Tasks
- [ ] Remove dropdown
- [ ] Remove the column for mood from the issue table on the database
- [ ] Remove the badge from the issue
- [ ] Remove all other dependencies to the field
