### ISSUE TITLE
Add subscription option on issues and subscription management

### ISSUE THREAD

**Issue by hlokomani** [COS301-SE-2024/The-Republic#86]
Users should be able to subscribe to **issues, categories IN locations, or locations**. They must also be able to see everything they have subscribed to and manage it. Subscribing should only be possible on issues that are not theirs, of course.

**Subtasks:**

- [ ] Add"Subscribe" option in "More" menu.
- [ ] Implement `SubscriptionDialog` component. This is a popup/overlay/modal component that asks the user what they want to subscribe to.
- [ ] If a user has already subscribed to an issue, the More menu should say unsubscribe.
- [ ] Create a way for users to be able to see all their subscriptions and manage them. This can be in the Notifications page or under settings. Your choice, as long as you justify.
